version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - npm install
      - npm run build
  artifacts:
    files:
      - '**/*'
  cache:
    paths:
      - './node_modules/**/*'
