version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - npm install
      - npm run build
  artifacts:
    files:
      - dist/**/*
  cache:
    paths:
      - ./node_modules/**/*
