version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - dist/**/*
cache:
  paths:
    - ./node_modules/**/*
